//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserSignupLogin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class TBLUserInfo
    {
        public int IdUs { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [Display(Name = "Username")]
        public string UsernameUs { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        public string PasswordUs { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [Display(Name = "Repeat password")]
        [DataType(DataType.Password)]
        [NotMapped]
        [Compare("PasswordUs", ErrorMessage ="Confirm password doesn't match, try again bitch!")]
        public string RePasswordUs { get; set; }
    }
}
